#lang sicp

(#%require "common.scm")

;   Exercise 1.9
;   ============
;   
;   Each of the following two procedures defines a method for adding two
;   positive integers in terms of the procedures inc, which increments its
;   argument by 1, and dec, which decrements its argument by 1.
;   
;   (define (+ a b)
;     (if (= a 0)
;         b
;         (inc (+ (dec a) b))))
;   
;   (define (+ a b)
;     (if (= a 0)
;         b
;         (+ (dec a) (inc b))))
;   
;   Using the substitution model, illustrate the process generated by each
;   procedure in evaluating (+ 4 5).  Are these processes iterative or
;   recursive?
;   
;   ------------------------------------------------------------------------
;   [Exercise 1.9]:  http://sicp-book.com/book-Z-H-11.html#%_thm_1.9
;   1.2.1 Linear Recursion and Iteration - p36
;   ------------------------------------------------------------------------

(-start- "1.9")



(--end-- "1.9")

